config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}


  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'pricing'
      get 'amenities'
      get 'location'
    end
    resources :photos, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  validates :fullname, presence: true, length: {maximum: 40}

  has_many :rooms

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.fullname = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider

        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.skip_confirmation!
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys:[:fullname, :phone_number, :description])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @room = Room.find(params[:room_id])

    if params[:images]
      params[:images].each do |img|
        @room.photos.create(image: img)
      end
      @photos = @room.photos
      redirect_back(fallback_location: request.referrer, notice: 'Saved...')
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @room = @photo.room

    @photo.destroy
    @photos = Photo.where(room_id: @room.id)

    respond_to :js
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorized, only: [:listing,:pricing, :photo_upload, :amenities, :location, :update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saving"
    else
      flash[:alert] = 'Something went wrong..'
      render :new
    end
  end

  def show
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update
    new_params = room_params
    new_params = room_params.merge(active: true) if is_ready_room

    if @room.update(new_params)
      flash[:notice] = "Saving"
    else
      flash[:alert] = "Something went wrong.."
    end
    redirect_back(fallback_location: request.referer)
  end


  private
    def set_room
      @room = Room.find(params[:id])
    end

    def is_authorized
      redirect_to root_path, alert: 'You do not have permission' unless current_user.id == @room.user_id
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_heating, :is_kitchen, :is_air, :is_internet, :price, :active)
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)

    if user.image
      "http://graph.facebook.com/#{user.uid}/picture?type=large" 
    else
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=mm"
    end

  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirPika</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/message' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Hello, World!</p>

app/views/photos/_photo_list.html.erb
<% if @photos.count > 0 %>
 <br/><br/>

 <div class="row">
   <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to room_photo_path(photo.room_id, photo), remote: true, method: :delete, data: {confirm: "Are You Sure?"} do %>
                <i class="fas fa-trash"></i>      
              <% end %>
            </span>
          </div>
        </div>
      </div>
   <% end %>
 </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photo_list' %>")

<% if @room.photos.blank? %>
$('#photo_check').hide()
<% end %>

<% if !@room.active && !@room.price.blank? && !@room.listing_name.blank? &&     !@room.photos.blank? && !@room.address.blank? %>
 $('#publish_button').attr('disabled', false)
<% else %>
 $('#publish_button').attr('disabled', true)
<% end %>

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to 'Listing', listing_room_path, class: "sidebar-link active"%>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to 'Pricing', pricing_room_path, class: "sidebar-link active"%>
    <% if !@room.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to 'Description', description_room_path, class: "sidebar-link active"%>
    <% if !@room.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to 'Photos', photo_upload_room_path, class: "sidebar-link active"%>
    <% if !@room.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to 'Amenities', amenities_room_path, class: "sidebar-link active"%>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to 'Location', location_room_path, class: "sidebar-link active"%>
    <% if !@room.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>

<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Amenities
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

          <div class="row form-group">
            <div class="col-md-4">
              <%= f.check_box :is_tv %> TV
            </div>
            <div class="col-md-4">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>
            <div class="col-md-4">
              <%= f.check_box :is_internet %> Internet
            </div>
          </div>

          <div class="row form-group">
            <div class="col-md-4">
              <%= f.check_box :is_heating %> Heating
            </div>
            <div class="col-md-4">
              <%= f.check_box :is_air %> Air Conditioning
            </div>
          </div>
          <br/><br/>

          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">

    <div class="panel panel-default">
      <div class="panel-heading">
        Description
      </div>

      <div class="panel-body">
        <div class="container">

          <%= form_for @room do |f| %>
            <div class="row">
              <div class="form-group">
                <label>Listing Name</label>
                <%= f.text_field :listing_name, placeholder: "Listing name", class: "form-control", required: true %>
              </div>
            </div>
            <div class="row">
              <div class="form-group">
                <label>Summary</label>
                <%= f.text_field :summary, row: 5, placeholder: "Summary of your home.", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<h1>Room#index</h1>
<p>Find me in app/views/room/index.html.erb</p>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">

    <div class="panel panel-default">
      <div class="panel-heading">
        Listing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
            <div class="row">
              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Home Type</label>
                  <%= f.select :home_type, [['Apartment', 'Apartment'],['House', 'House'],['Bed & Breakfast', 'Bed & Breakfast']],
                  id: 'home_type', prompt: 'Select...', class:'form-control' %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Room Type</label>
                  <%= f.select :room_type, [['Entire', 'Entire'],['Private', 'Private'],['Shared', 'Shared']],
                  id: 'room_type', prompt: 'Select...', class:'form-control' %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Accommodate</label>
                  <%= f.select :accommodate, [['1', 1],['2', 2],['3', 3], ['4+', 4]],
                  id: 'accommodate', prompt: 'Select...', class:'form-control' %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Bedrooms</label>
                  <%= f.select :bed_room, [['1', 1],['2', 2],['3', 3], ['4+', 4]],
                  id: 'bed_room', prompt: 'Select...', class:'form-control' %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Bathrooms</label>
                  <%= f.select :bath_room, [['1', 1],['2', 2],['3', 3], ['4+', 4]],
                  id: 'bath_room', prompt: 'Select...', class:'form-control' %>
                </div>
              </div>
            </div>

            <div><%= f.submit "Save", class: "btn btn-normal"%></div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Location
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
            <div class="row">
              <div class="form-group">
                <label>Address</label>
                <%= f.text_field :address, placeholder: "What is your address?", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your special place!
  </div>

  <div class="panel-body">
    <div class="container">

      <%= form_for @room do |f| %>
      
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [['Apartment', 'Apartment'],['House', 'House'],['Bed & Breakfast', 'Bed & Breakfast']],
              id: 'home_type', prompt: 'Select...', class:'form-control' %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [['Entire', 'Entire'],['Private', 'Private'],['Shared', 'Shared']],
              id: 'room_type', prompt: 'Select...', class:'form-control' %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accommodate</label>
              <%= f.select :accommodate, [['1', 1],['2', 2],['3', 3], ['4+', 4]],
              id: 'accommodate', prompt: 'Select...', class:'form-control' %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedrooms</label>
              <%= f.select :bed_room, [['1', 1],['2', 2],['3', 3], ['4+', 4]],
              id: 'bed_room', prompt: 'Select...', class:'form-control' %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathrooms</label>
              <%= f.select :bath_room, [['1', 1],['2', 2],['3', 3], ['4+', 4]],
              id: 'bath_room', prompt: 'Select...', class:'form-control' %>
            </div>
          </div>
        </div>

        <div><%= f.submit "Create my room", class: "btn btn-normal" %></div>
      <% end %>

    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">

    <div class="panel panel-default">
      <div class="panel-heading">
        Photos
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->
              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>

                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fas fa-trash"></i> Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Add Photos", class:"btn btn-form" %>
                </div>

              <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'photos/photo_list' %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Pricing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
            <div class="row">
              <div class="form-group">
                <label>Price</label>
                <%= f.text_field :price, placeholder: "Money, please." , class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key,value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">AirPika</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if (!user_signed_in?) %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;<%= current_user.fullname %>&nbsp;<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Manage Listing</a></li>
              <li><a href="#">List Space</a></li>
              <li><a href="#">Your Reservation</a></li>
              <li><a href="#">Your Trips</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>


      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="center">
      <%= image_tag avatar_url(@user), class: "avatar-full"%>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">Verification</div>
      <div class="panel-body">
        Email Address<br/>
        Phone Number
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <h2><%= @user.fullname %></h2>
    <div class="description row-space-3">
      <%= @user.description %>
    </div>
  </div>
</div>